### ISSUE TITLE
Add the possiblity to download pulsar instead of building it from scratch

### ISSUE THREAD

**Issue by ndr-brt** [pulsar-edit/action-pulsar-dependency#3]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

Currently the plugin builds pulsar from scratch using `yarn build`, this takes too much time, it could be helpful to have a way to run the plugin downloading and installing pulsar as the old `UziTech/action-setup-atom` did.

### What benefits does this feature provide?

faster builds

### Any alternatives?

maybe caching? doesn't seem a good alternative though

**Comment by confused-Techie** [comment]
I avoided this originally, because we didn't have an easy way to download the most recent editor build. But now with the download endpoint we do.

Plus to be completely honest this test runner is in a non-working state unfortunately, and I last spec way to long trying to get it to work.

So maybe switching to a binary of the editor is the way to go here.

**Comment by ndr-brt** [comment]
In the meantime I ended up doing it like this, only for ubuntu, but it shouldn't be that harder to extend it to win and mac: https://github.com/tidalcycles/atom-tidalcycles/blob/master/.github/workflows/ci.yml
